test if condition

diff --git a/.github/workflows/github-run-main.yml b/.github/workflows/github-run-main.yml
--- a/.github/workflows/github-run-main.yml
+++ b/.github/workflows/github-run-main.yml
@@ -30,5 +30,9 @@ jobs:
           git config user.name github-run-main-action
           git config user.email github-run-main-action@github.com
           git add images/.
-          git commit -m "auto-update at `date +'%Y-%m-%d %H:%M:%S'`"
-          git diff-index --quiet HEAD || git push
+          if ! git diff-index --quiet HEAD; then
+            git commit -m "auto-update at `date +'%Y-%m-%d %H:%M:%S'`"
+            git push
+          else
+            echo "ignore commit failure, proceed"
+          fi
